project:
  type: website

website:
  title: "Biomarkers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar: 
    style: "docked"
    search: true
    contents:
      - section: "NSCLC"
      - section: "Breast"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

