project:
  type: website

website:
  title: "Biomarkers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: General Info
  sidebar: 
    style: "docked"
    search: true
    contents:
      - section: "NSCLC"
        contents:
          - section: "EGFR"
            contents: 
              - href: EGFR_del19.qmd
                text: Exon 19 deletion
              - href: EGFR_ex20ins.qmd
                text: Exon 20 insertions
              - href: EGFR_E709.qmd
                text: E709
              - href: EGFR_G719.qmd
                text: G719X
              - href: EGFR_L858R.qmd
                text: L858R
              - href: EGFR_L861Q.qmd
                text: L861Q
              - href: EGFR_S768I.qmd
                text: S768I
              - href: EGFR_T790M.qmd
                text: T790M
      - section: "Breast"
        contents: 
          - href: BRCA12.qmd
            text: BRCA1/2
          - href: ER.qmd
          - href: PD1.qmd
            text: PD-1
          - href: PDL1.qmd
            text: PD-L1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

