---
title: "General Information and Recommendations"
---

Biomarker recommendations will be updated quarterly. Each page will indicate whether the code has been updated for the current quarter's data release.

Biomarker recommendations are based on what has been confirmed by looking in EMOL patient records, and inconsistencies that may be present. The goal is to be as thorough as possible, but if you see something that needs to be changed, please let me know. \[link to email or jira\]

If you do not see the biomarker or variant that you need, it may be in progress. However, just in case, submit your biomarker, variant, and indication here. \[link to email or jira\]<br><br>

**Of Note**: <br> - When pulling biomarker records from GN360, it may be necessary to query both genetic_test and patient_test tables. We found that in some cases, for some genes/biomarkers, there are patients listed in patient_test that are not in genetic_test. Because of this, please remember to check both tables, and add results from patient_test to genetic_test when necessary. Code in this manual adds patients from both tables when applicable.<br><br> - In general, if you see that some records are marked as "Suppressed" it is best to exclude them from your counts, especially if the goal is to find number of positive tests for a particular biomarker.

**Abbreviations** <br> - AA: amino acid <br> - CDS: coding sequence <br> - TKIs: Tyrosine kinase inhibitors<br> - IHC: Immunohistochemistry<br>
