---
title: "EGFR G719X"
---

*Code updated for Q4 2022*

This variant, located on exon 18, is a single nucleotide missense mutation changing Glycine (Gly) to another amino acid, commonly to Alanine (Ala).

See <a href="https://www.ncbi.nlm.nih.gov/clinvar/?term=G719+EGFR">ClinVar</a> for more information.<br><br>

**AA mutation**: p.G719X (X could be D, A, R, S, C, or possibly others) <br> **CDS mutation**: c.2155G\>A, c.2155G\>C, c.2155G\>T, c.2156G\>A, c.2156G\>C

## Example Code: PT360

```{sql}
select chai_patient_id,
       test_name_name,
       test_date,
       test_collection_date,
       genetic_test_type_name,
       test_method_name,
       molecular_variant_name,
       test_value_name,
       curation_indicator
       from c3_pt360_202212_nsclc.patient_test
    where test_name_name like '%EGFR%' AND
          molecular_variant_name similar to '%(G719|Gly719|c.215_G)%' and
          molecular_variant_name <> 'G7195 8709 a' and
          test_method_name not in ('Immunohistochemistry or immunocytochemistry, per specimen; initial single antibody stain procedure',
                                  'Molecular cytogenetics; DNA probe, each (eg, FISH)') and
          lower(genetic_test_type_name) not similar to '%(amp|del)%' and 
          test_value_name = 'Positive';
```

## Example Code: GN360

```{sql}
select chai_patient_id,
       test_name_name,
       test_date,
       genetic_test_type_name,
       test_method_name,
       molecular_variant_name,
       'p.G719X' as protein_alteration,
       test_value_name

from c3_gn360_202212_nsclc.patient_test

where test_name_name like '%EGFR%' and
      molecular_variant_name similar to '%(G719|Gly719|c.215_G)%' and
          molecular_variant_name <> 'G7195 8709 a' and
          test_method_name not in ('Immunohistochemistry or immunocytochemistry, per specimen; initial single antibody stain procedure',
                                  'Molecular cytogenetics; DNA probe, each (eg, FISH)') and
      lower(genetic_test_type_name) not similar to '%(amp|del)%'
      and test_value_name = 'Positive'

UNION

select chai_patient_id,
       biomarker_name as test_name_name,
       report_date as test_date,
       biomarker_test_type as genetic_test_type_name,
       'NGS' as test_method_name,
       dna_alteration as molecular_variant_name,
       protein_alteration,
       test_result as test_value_name
from c3_gn360_202212_nsclc.genetic_test
where biomarker_name = 'EGFR' AND
          protein_alteration similar to '%G719%'and
          test_value_name = 'Positive';
```

## Notes and Recommendations

-   Notice that IHC and FISH are being removed as test methods. There is some evidence that there are ways to identify some variants of EGFR via IHC, but after checking the patient records that have these methods listed, it was actually found that the test method *should* be listed as PCR or NGS. The patient(s) marked as having FISH as a method is also incorrect.<br />

-   Note that genetic test types similar to `'%(amp|del)%'` are being removed. This is removing `Gene amplification` and `Gene deletion`. These are inaccurate since this is a missense mutation.<br />
